---
- name: Sync all PAH EE and Remote Repos for testing
  hosts: localhost
  gather_facts: false
  become: false
  tags: sync

  roles:
    - sync_ee
    - sync_repos

- name: Build new shadowmancreationee
  hosts: ansibledev.shadowman.dev
  tags: buildee

  roles:
    - build_creationee
